In [ ]:
# Create a random tensor with shape (7,7)

import torch

random_tensor = torch.rand(7,7)
random_tensor, random_tensor.shape

(tensor([[0.7308, 0.8694, 0.1932, 0.8097, 0.0048, 0.6487, 0.7315],
         [0.5571, 0.0369, 0.6796, 0.0645, 0.3965, 0.5692, 0.0581],
         [0.7381, 0.5473, 0.7307, 0.5893, 0.5047, 0.5895, 0.2430],
         [0.3447, 0.4645, 0.6874, 0.5117, 0.8003, 0.1585, 0.1209],
         [0.9569, 0.2046, 0.3154, 0.7036, 0.0422, 0.2496, 0.8109],
         [0.5795, 0.9842, 0.6968, 0.8748, 0.2238, 0.7562, 0.5154],
         [0.8414, 0.6772, 0.7167, 0.0959, 0.7896, 0.1944, 0.6711]]),
 torch.Size([7, 7]))

In [ ]:
#Perform a matrix multiplication on the tensor from 2 with another
#random tensor with shape (1, 7) (hint: you may have to transpose the second tensor)

In [ ]:
another_tensor = torch.rand(1,7)
another_tensor,another_tensor.shape

(tensor([[0.5868, 0.8685, 0.8801, 0.4335, 0.1301, 0.1471, 0.1723]]),
 torch.Size([1, 7]))

In [ ]:
tensorResult1 = torch.matmul(random_tensor, another_tensor)
tensorResult1

RuntimeError: mat1 and mat2 shapes cannot be multiplied (7x7 and 1x7)

In [ ]:
new_another = another_tensor.T
new_another, new_another.shape

(tensor([[0.5868],
         [0.8685],
         [0.8801],
         [0.4335],
         [0.1301],
         [0.1471],
         [0.1723]]),
 torch.Size([7, 1]))

In [ ]:
tensorResult1 = torch.matmul(random_tensor, new_another)
tensorResult1, tensorResult1.shape

(tensor([[1.9270],
         [1.1302],
         [2.0012],
         [1.5807],
         [1.5037],
         [2.4164],
         [2.0011]]),
 torch.Size([7, 1]))

In [ ]:
# Set random seed to 0 and do exercises 2 & 3 over again

import torch
random_seed = 0

torch.manual_seed(random_seed)
random_tensor = torch.rand(7,7)
random_tensor.shape

torch.manual_seed(random_seed)
another_tensor = torch.rand(1,7)
another_transpose = another_tensor.T


tensorResult1 = torch.matmul(random_tensor, another_transpose)
tensorResult1, tensorResult1.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

In [ ]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?
 # (hint: you'll need to look into the documentation for torch.cuda for this one).
# If there is, set the GPU random seed to 1234.

gpu_random_seed = 1234
gpu_random = torch.cuda.manual_seed(gpu_random_seed)
print(gpu_random)





None


In [ ]:
#Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this).
# Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

import torch
torch.manual_seed(1234)

random_tensor = torch.rand(2,3)

another_tensor = torch.rand(2,3)

device = "cuda" if torch.cuda.is_available() else "cpu"

random_tensor.to(device), another_tensor.to(device)

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [ ]:
#Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors

matrix_mul_2 = torch.matmul(random_tensor, another_tensor.T)
matrix_mul_2

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

In [ ]:
#Find the maximum and minimum values of the output of 7.
matrix_mul_2.min(), matrix_mul_2.max()

(tensor(0.3647), tensor(0.5617))

In [ ]:
#Find the maximum and minimum index values of the output of 7.
matrix_mul_2.argmin(), matrix_mul_2.argmax()

(tensor(0), tensor(3))

In [ ]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10).
# Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
import torch
set_seed = 7
torch.manual_seed(set_seed)
tensor_index = torch.rand(1, 1, 1, 10)

torch.manual_seed(set_seed)
tensor_to_squeeze = tensor_index.squeeze()


print(tensor_index, tensor_index.shape)
print(tensor_to_squeeze, tensor_to_squeeze.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
